version: '3.8'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: development
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:pass@server/datab
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: datab
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
